### ISSUE TITLE
how to run inference

### ISSUE THREAD

**Issue by eschmidbauer** [Choddeok/EmoSpherepp#1]
Hi!
Thank you for sharing this project and checkpoint
Can you share an example inference script? I'd really like to test/evaluate the pretrained checkpoint you shared.

**Comment by Choddeok** [comment]
Hello,

Thank you for your interest in my paper and code.

The requested inference script is included in the `train_run.sh` file. You can use the pretrained checkpoint for inference by modifying the **GEN_DIR** or **work_dir** sections to specify the appropriate paths.

I plan to update the scripts to make them more user-friendly in the future. Additionally, I will organize and release the evaluation metric code in a new repository soon.

**Comment by suckrowPierre** [comment]
I tried running `preprocessing.sh` but then get the error:

```
Load meta data: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/align_and_binarize.py", line 9, in <module>
    preprocess()
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/data_gen/tts/runs/preprocess.py", line 12, in preprocess
    process_cls().process()
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/data_gen/tts/base_preprocess.py", line 45, in process
    meta_data = list(tqdm(self.meta_data(), desc='Load meta data'))
  File "/home/pierre/miniconda3/envs/emospherepp/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/egs/datasets/audio/esd/preprocess.py", line 6, in meta_data
    for l in open(f'{self.raw_data_dir}/esd_text_emo.txt').readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/choddeok/hd0/dataset/ESD_mfa_sum/esd_text_emo.txt'
```

**Comment by suckrowPierre** [comment]
Also when running the train script I get the error:


```
Traceback (most recent call last):
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/tasks/run.py", line 19, in <module>
    run_task()
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/tasks/run.py", line 13, in run_task
    task_cls = getattr(importlib.import_module(pkg), cls_name)
  File "/home/pierre/miniconda3/envs/emospherepp/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/tasks/tts/EmoSpherepp.py", line 2, in <module>
    from tasks.tts.speech_base import SpeechBaseTask
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/tasks/tts/speech_base.py", line 14, in <module>
    from tasks.tts.dataset_utils import BaseSpeechDataset
  File "/home/MotivationalSpeechSynthesis/EmoSpherepp/tasks/tts/dataset_utils.py", line 13, in <module>
    from utils.text import intersperse
ImportError: cannot import name 'intersperse' from 'utils.text' (unknown location)
```

**Comment by Choddeok** [comment]
@suckrowPierre 

Thank you for your interest in my paper and code.

Regarding the error you mentioned, it seems to be caused by a missing or incorrect path to the esd_text_emo.txt file. To resolve this issue, please ensure that the file path is correctly specified in your working environment.

Check the directory where esd_text_emo.txt is located.
Update the code to reflect the correct path for your setup.
Once the file path is correctly set, the preprocessing step should run without issues.

Additionally, I will update the code with more detailed explanations to make it easier to follow and learn.

I apologize for the delayed response and appreciate your patience. Thank you again for bringing this to my attention! 😊

**Comment by suckrowPierre** [comment]
@Choddeok but where do I get this `esd_text_emo.txt`? The ESD dataset provides text files with file names, transcriptions, and emotions. But looking at the code in `egs/datasets/esd/preprocess.py` it needs txt file separated by "|". Did you create your `esd_text_emo. txt` file be appending each of those text files of the dataset to one and changing the separator?

**Comment by Choddeok** [comment]
@suckrowPierre 


You can find the esd_text_emo.txt file included in the provided GitHub repository. Please check the repository and configure the directory path accordingly.

https://github.com/Choddeok/EmoSpherepp/blob/main/esd_text_emo.txt

**Comment by CreepJoye** [comment]
@Choddeok 
Hello,

First of all, thank you so much for your hard work and for making this project open-source. I really appreciate it.

I would like to inquire if you could share a simplified version of the inference code and the process for running inference using the provided checkpoint. I am particularly interested in using the checkpoint that you've shared for the inference task.

Your help would be greatly appreciated!

Thank you!

**Comment by Choddeok** [comment]
@CreepJoye 
Hello,

Thank you very much for your interest in the project. I'm truly sorry for the delayed response.

To run inference using the provided checkpoint, please set the work_dir path in the config_base.yaml file. Once you've specified the path, place the checkpoint file in that directory. After this setup, you should be able to proceed with inference without any issues.

If you encounter any problems or have further questions, feel free to reach out.

**Comment by wesferr** [comment]
Hello @Choddeok, can you provide a detailed inference guide? i'm not from AI, and need to run this model.

**Comment by Choddeok** [comment]
@wesferr 
Hello, sorry for the late reply.

At the moment, the framework is not structured in a way that makes simple inference very straightforward, so it might be a bit difficult to run it directly for inference right now.

You would need to follow the preprocessing steps and create binary files for inference samples, similar to how it is done in the NATSpeech framework:
https://github.com/NATSpeech/NATSpeech

However, I understand that this process can be quite challenging, especially if you're not familiar with AI workflows.

I will try to improve the accessibility and make the inference process easier to use in the future.

If you have specific parts you're stuck on, feel free to let me know and I’ll do my best to help.
